name: gma_mediation_chartboost
description: 'Mediation Adapter that enables sending ad requests to the Chartboost
  ad network using the google_mobile_ads plugin.'
version: 1.0.1
environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.2.0
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  pigeon: ^22.6.2
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_chartboost
        pluginClass: GmaMediationChartboostPlugin
      ios:
        pluginClass: GmaMediationChartboostPlugin
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/mediation/gma_mediation_chartboost
