name: gma_mediation_line
description: 'Mediation Adapter that enables sending ad requests to the Line
  ad network using the google_mobile_ads plugin.'
version: 1.0.1
environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.3.1
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lint: ^2.3.0
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_line
        pluginClass: GmaMediationLinePlugin
      ios:
        pluginClass: GmaMediationLinePlugin
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/mediation/gma_mediation_line
