name: gma_mediation_dtexchange
description: "Mediation Adapter that enables sending ad requests to the DT Exchange ad network using the google_mobile_ads plugin."
version: 1.1.3
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/mediation/gma_mediation_dtexchange

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  pigeon: ^19.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_dtexchange
        pluginClass: GmaMediationDTExchangePlugin
      ios:
        pluginClass: GmaMediationDTExchangePlugin
