#  Copyright 2021 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: google_mobile_ads

on:
  pull_request:
    paths:
      - "packages/google_mobile_ads/**"
      - ".github/workflows/google_mobile_ads.yaml"
      - "packages/google_mobile_ads/ios/**"
      - "packages/google_mobile_ads/android/**"
  push:
    branches:
      - master

env:
  GOOGLEMOBILEADS_PLUGIN_SCOPE: "*google_mobile_ads*"
  GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE: "*google_mobile_ads_example*"
jobs:
  android:
    runs-on: macos-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-example.sh android ./lib/main.dart packages/google_mobile_ads/example
      - name: "Unit Tests"
        run: |
          cd packages/google_mobile_ads/example/android
          ./gradlew test

  iOS:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
      - name: "Build iOS Example"
        run: ./.github/workflows/scripts/build-example.sh ios ./lib/main.dart packages/google_mobile_ads/example
      - name: "Unit Tests"
        run: |
          cd packages/google_mobile_ads/example/ios
          flutter clean
          flutter pub get
          pod install
          xcodebuild -configuration Debug -resultBundlePath TestResults VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' test  
      - uses: actions/upload-artifact@v3
        if: failure()
        with: 
          name: iOSTestResults
          path: packages/google_mobile_ads/example/ios/TestResults.xcresult  
  flutter:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Unit Tests"
        run: |
          cd packages/google_mobile_ads/
          flutter test
      - name: "Flutter Analyze"
        run: |
          cd packages/google_mobile_ads/
          flutter analyze
      - name: "Flutter Publish"
        run: |
          cd packages/google_mobile_ads/
          flutter pub publish --dry-run
      - name: "Flutter Format"
        run: |
          flutter pub global activate flutter_plugin_tools
          flutter pub global run flutter_plugin_tools format
          ./.github/workflows/scripts/validate-formatting.sh
